
GEt http://localhost:3000/players
###
GET http://localhost:3000/players/1/

###   check
put http://localhost:3000/players/1/                       

Content-Type: application/json
body:
{
  "playerName": "Raju"
}


####
GET http://localhost:3000/matches/17/

####
get http://localhost:3000/players/5/matches/

###
get http://localhost:3000/matches/1/players/

###
get http://localhost:3000/players/8/playerScores/
